name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Vault CLI
        run: |
          curl -o vault.zip https://releases.hashicorp.com/vault/1.10.4/vault_1.10.4_linux_amd64.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/  

      - name: Login to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          method: token

      - name: Get AWS credentials from Vault
        id: get-aws-creds
        run: |
          aws_creds=$(vault kv get -format=json secret/aws/ecr | jq -r .data)
          echo "::set-output name=aws_access_key_id::$(echo $aws_creds | jq -r .access_key_id)"
          echo "::set-output name=aws_secret_access_key::$(echo $aws_creds | jq -r .secret_access_key)"

      - name: Configure Docker to use AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ steps.get-aws-creds.outputs.aws_access_key_id }}
          aws configure set aws_secret_access_key ${{ steps.get-aws-creds.outputs.aws_secret_access_key }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/my-image:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/my-image:latest
